name: CD Pipeline

permissions:
  packages: write

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Compile and test application
        run: |
          chmod +x gradlew
          ./gradlew build
  package:
    name: Package
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Get project version
        uses: thecodemonkey/action-get-gradle-version@master
        id: version
      - name: Save app version as environment variable
        run: |
          echo "APP_VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV
      - name: Containerize and publish image
        run: |
          chmod +x gradlew
          ./gradlew bootBuildImage \
            --imageName ghcr.io/npalm/catalog-service:${{ env.APP_VERSION }} \
            --publishImage \
            -PregistryUrl=ghcr.io \
            -PregistryUsername=npalm \
            -PregistryToken=${{ secrets.GITHUB_TOKEN }}
