name: CI Pipeline
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Compile and test application
        run: |
          chmod +x gradlew
          ./gradlew build
